require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

IOS_VERSION = '13.4'

platform :ios, IOS_VERSION

install! 'cocoapods', :deterministic_uuids => false

target 'ReactNativeAntMediaExample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    #hermes is enabled by default, we also need to define following macro to make it build because of this error https://github.com/facebook/react-native/issues/38193#issuecomment-2071511755
    #- Find Preprocessor Macros inside Apple Clang - Preprocessing section.
    # -Add USE_HERMES=1 for both Debug and Release configurations.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ReactNativeAntMediaExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
             config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_VERSION
      end
    end

  end



end
