name: "publish"

on:
   push:
     branches: [ main ]

permissions:
   contents: read
   id-token: write

jobs:
  publish:
     name: publishing
     runs-on: ubuntu-latest

     steps:
        - name: checkout
          uses: actions/checkout@v6
        - name: installation of node
          uses: actions/setup-node@v6
          with:
            node-version: 24
            registry-url: 'https://registry.npmjs.org'
            package-manager-cache: false

        - name: install dependencies
          run: npm ci

        - name: publish
          run: npm publish --access public
          env:
            NODE_AUTH_TOKEN: ''
            NPM_TOKEN: ''
