name: "publish"

on:
   push:
     branches: [ main ]

jobs:
  publish:
     name: publishing
     runs-on: ubuntu-latest

     steps:
        - name: checkout
          uses: actions/checkout@v3.0.2
        - name: installation of node
          uses: actions/setup-node@v4
          with:
            node-version: 20
            registry-url: 'https://registry.npmjs.org'
            scope: '@antmedia'
            always-auth: true

        - name: verify npm authentication
          run: npm whoami
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        - name: publish
          run: |
           npm ci
           npm publish --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
